spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/kk?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
  rocketmq:
    #name-server: 192.168.1.116:9876
    name-server: 10.11.46.100:9876

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html

kk:
  framework-web:
    swagger:
      enabled: true
      name: base-git-dev-4
    cors:
      enabled: true
    xss:
      enabled: true
    event:
      enabled: true
      executor:
        poolsize: 100
    sql-log:
      enabled: true
  authorization:
    enabled: true
    token-manager:
      # 是否单点登录
      single-token-with-user: true
    interceptor:
      http-header-name: authorization
      unauthorized-error-message: 登录失效，请重新登录
    token-cache:
      tokenExpireSeconds: 604800
      user-login-type: MEMBER
  smsCodeValidMins: 5
  wx:
    mp:
      enabled: true
      appid: wx4204fdfb01794b59
      appsecret: f2ab14b4c8e95ba37bf10e4c7cb7a7a0